# Generated by Django 3.1.7 on 2021-02-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campsider', '0002_auto_20210225_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_scrap',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_scrapped',
            field=models.BooleanField(default=False),
        ),
    ]
